### ISSUE TITLE
Potential for client IP spoofing via `x-forwarded-for` header

### ISSUE THREAD

**Issue by ivarvong** [opentelemetry-beam/opentelemetry_phoenix#15]
I was browsing the repo and came across: https://github.com/opentelemetry-beam/opentelemetry_phoenix/blob/main/lib/opentelemetry_phoenix.ex#L186

A client making the HTTP request may include an `x-forwarded-for` header, allowing the client to override the true client IP, rather than using the value the load balancer sets. Load balancers often append the IP address of the client. Different environments handle this in different ways -- some set a "true IP" header [0], some explain how they handle the presence of an additional IP [1].

0: https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-
1: https://cloud.google.com/load-balancing/docs/https#x-forwarded-for_header

**Comment by bryannaegele** [comment]
Hey @ivarvong. The spec specifically calls for the `http.client_ip` to be derived from that header if present, so I _think_ that would be an infrastructure concern as to whether or not any client-supplied header is stripped at your ingress. It's ultimately up to you and your team as to which IPs you trust in your tooling. Also note that this isn't a required attribute, so it's at the user's discretion on how to utilize that information. At the end of the day, we try to adhere as closely to the spec as we can.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions

On the note of how load balancers/proxies handle this header, the IP of the the load balancer handling the request is appended to the list of IPs, not the other way around. In a list of IPs on that header the first IP is the remote client's, then the IPs of subsequent proxies are appended to the list. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

This could certainly be a concern if you were trying to use trace data for security purposes, but that's not the goal or a stated purpose of Otel.

Does that help?

**Comment by ivarvong** [comment]
Fair enough, thanks for the quick reply!
