### ISSUE TITLE
[Question] Controller span name

### ISSUE THREAD

**Issue by ricardoccpaiva** [opentelemetry-beam/opentelemetry_phoenix#19]
Hi :wave: 

What do you think of change the span name as the following diff suggests? 
![image](https://user-images.githubusercontent.com/2286067/109338640-6d3e7200-785e-11eb-89c8-23ca73b9528f.png)

Having Transactions "grouped" by just HTTP Verb seems a bit weird. Check the change here :point_down: 
![image](https://user-images.githubusercontent.com/2286067/109338757-95c66c00-785e-11eb-9565-8219e930ab3d.png)

Waiting for feedback from you. I'm ok with opening a PR, please let me know of your opinion.

**Comment by ricardoccpaiva** [comment]
@bryannaegele what do you think? Thanks in advance.

**Comment by bryannaegele** [comment]
Hey @ricardoccpaiva. 

This is covered in the spec. Span names on http requests at their most detailed have to be a parameterized name which the full request path violates. Note the differences between a client span name and the server span name.

We don't have access to the parameterized name until we get into a router match, so the verb is the best we can do at that particular point in the pipeline. The request path is an attribute. If you aren't getting a parametrized span name, that should indicate it isn't getting a route match in the phoenix router.

Based on the spec, this is working as required.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#name
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-client-server-example

**Comment by ricardoccpaiva** [comment]
> We don't have access to the parameterized name until we get into a router match, so the verb is the best we can do at that particular point in the pipeline.

sorry I didn't get this part. The function `handle_endpoint_start/4` has a map in the 3rd argument that has the `conn` map with all the information that we need. In my phoenix API I did nothing but change as I showed you in the diff and it worked like a charm.

>  The request path is an attribute. If you aren't getting a parametrized span name, that should indicate it isn't getting a route match in the phoenix router.

Can you be a bit more detailed? I tested this on my API and it is working, I'm getting always a route match.

**Comment by ricardoccpaiva** [comment]
and if do this change, all specs pass as well

````elixir
mix test                                                                                                                                                 ─╯
Compiling 1 file (.ex)

19:44:09.144 [info]  Application opentelemetry exited: :stopped
.
19:44:09.155 [info]  Application opentelemetry exited: :stopped
.
19:44:09.159 [info]  Application opentelemetry exited: :stopped
.

Finished in 0.1 seconds
3 tests, 0 failures

Randomized with seed 36202

**Comment by bryannaegele** [comment]
The `request_path` is the full target path, e.g. `/users/123` `/users/456`. That full target path is forbidden as a span name according to the Otel spec which I linked to above. The span name in the example given here has to be something like `/users/:id`. `handle_endpoint_start` does not have the correct value that we need at that point in the pipeline. The value is on `:route` which isn't available until the router event. https://github.com/opentelemetry-beam/opentelemetry_phoenix/blob/main/lib/opentelemetry_phoenix.ex#L146

The "spec" I as referring to is the Otel specification https://github.com/open-telemetry/opentelemetry-specification which has explicit standards on what all the names and values have to be. If you read through the links I posted that should answer any questions on what they have to be.

**Comment by ricardoccpaiva** [comment]
Now I see! Thanks for your clear explanation. 

Just one more thing, probably I'm missing something but `handle_router_dispatch_start/4` is never called and I don't know why :sweat_smile: 

**EDIT:** I've managed to execute the callback by putting `plug Plug.Telemetry, event_prefix: [:phoenix, :router_dispatch]
` in my router pipeline declaration but it's still wrong, it fails accessing `meta.plug` and `meta.plug_opts`

Any idea of what am I doing wrong?
Many thanks once again.

**Comment by ricardoccpaiva** [comment]
nevermind @bryannaegele, the problem was in the Phoenix version (v1.3.0) of the API i was testing otel.
Just did an update an.. :boom: :sweat_smile: 
awesome, thanks!

![image](https://user-images.githubusercontent.com/2286067/109364580-01bcca80-7887-11eb-9fca-0c01a1fab7fb.png)
