### ISSUE TITLE
spans based on [:phoenix, :endpoint] vs [:cowboy, :request]

### ISSUE THREAD

**Issue by dvic** [opentelemetry-beam/opentelemetry_phoenix#28]
This library relies on `[:phoenix, :endpoint, :stop]` which, as I understand it, is emitted by `Plug.Telemetry`. However, we've been seeing in production (previously with openconsensus) request durations that are too optimistic. I believe this is because the stop event is emitted before the actual data is sent over the wire. From https://github.com/elixir-plug/plug/blob/f7fbe26e7148374c4d37bde41540be2844056aa1/lib/plug/telemetry.ex#L22-L24 I read

*Note this plug measures the time between its invocation until a response is sent. The `:stop` event is not guaranteed to be emitted in all error cases, so this Plug cannot be used as a Telemetry span.*

This is why I'm currently investigating to the creation of spans using the metrics emitted by https://hexdocs.pm/plug_cowboy/Plug.Cowboy.html#module-instrumentation, which should give us more accurate spans (but I'm not sure how to exactly pass the parent context https://github.com/open-telemetry/opentelemetry-erlang/issues/182#issuecomment-887351898.

Maybe this is something that this library might consider as well in the future? However I'm not sure how to handle the case when someone is not using Cowboy (or if that case needs to be supported).

**Comment by dvic** [comment]
I've been playing around and this might be an option: create the parent span inside a cowboy stream handler, and inject the context into the headers using `:otel_propagator.text_map_inject`. This project would automatically pick this up right? This could however be a separate contrib project? `opentelemetry_cowboy`?

Defining and using a Cowboy stream handler in Elixir:

```elixir
defmodule DemoWeb.CowboyHandler do
  @behaviour :cowboy_stream

  # implement all opentelemtry logic in this module

  @impl true
  def init(stream_id, req, opts) do
    :cowboy_stream_h.init(stream_id, req, opts)
  end

  @impl true
  def info(stream_id, info, state) do
    :cowboy_stream_h.info(stream_id, info, state)
  end

  @impl true
  def data(stream_id, is_fin, data, state) do
    :cowboy_stream_h.data(stream_id, is_fin, data, state)
  end

  @impl true
  def terminate(stream_id, reason, state) do
    :cowboy_stream_h.terminate(stream_id, reason, state)
  end

  @impl true
  def early_error(stream_id, reason, partial_req, resp, opts) do
    :cowboy_stream_h.early_error(stream_id, reason, partial_req, resp, opts)
  end
end
```

and then in `dev.exs`

```elixir
stream_handlers: [:cowboy_telemetry_h, DemoWeb.CowboyHandler]
```

**Comment by bryannaegele** [comment]
@dvic we've had code in the past that checked if we were already in a span before running the extractors but that was before the ctx idea got implemented.

@tsloughter- can we get away with that approach still or are there gotchas do to the process boundary crossing? I think the latter is true and why I dropped it.

**Comment by bryannaegele** [comment]
To the question about where the code would go, we would want to create a different instrumentation library for that as phoenix isn't technically required to run on cowboy and there are some advanced things to consider when tracing higher up the call stack that the average user wouldn't be prepared for.

Ideally we'd like better integration points directly into Phoenix but this is what we can do for now :)

**Comment by dvic** [comment]
> @tsloughter- can we get away with that approach still or are there gotchas do to the process boundary crossing? I think the latter is true and why I dropped it.

@bryannaegele What gotchas are you referring to? The context propagation as I described it above, assuming the implementation is correct, should work, right? Or do you mean that previously you set the current span to be the parent span (using https://hexdocs.pm/opentelemetry_api/1.0.0-rc.2/OpenTelemetry.Tracer.html#set_current_span/1)?

> To the question about where the code would go, we would want to create a different instrumentation library for that as phoenix isn't technically required to run on cowboy and there are some advanced things to consider when tracing higher up the call stack that the average user wouldn't be prepared for. 

I agree, but I was also surprised by the fact that durations for some of our calls (large response of large IO data) were way off, didn't think of this at the time :) It makes me wonder if Phoenix is the correct abstraction layer to do this type of (HTTP) tracing. How I see it currently is that the adapter (cowboy in most cases) should be the one tracing the HTTP stuff and Phoenix should be tracing the framework specific stuff (plugs, the endpoint itself, etc.) But if there should be two different spans here: I'm not quite sure (see also my comment above about the gotchas).

**Comment by bryannaegele** [comment]
Gotchas being you're now tracing every possible hit to the server which can quickly DDOS or escalate your trace generation without a significant amount of filtering which we don't currently have great facilities for. I'm probably an "advanced user" of otel in erlang/elixir and I wouldn't attempt it 😆 

For the span stuff, if we cross process boundaries then we have to propagate the ctx. If we did do it with injecting headers again at the cowboy level, you will have to modify the existing headers by deleting the existing traceparent header before injecting the new one. I don't think the propagators currently support overwriting.

As for tracing at Phoenix vs at the adapter, the adapter is in no way able to provide all of the required attributes and can't even name the span properly. Until the request is actually routed and parsed, there's not a lot of info available.

I think what you've described would technically work but I don't think the spans would end up how you're expecting them. We'd still be creating a new span in Phoenix which would have all of the required info and a higher level span in cowboy which has much less. I do believe that is the only solution at this time, however. This is just a fundamental issue of how cowboy and everything else works, unfortunately.

**Comment by bryannaegele** [comment]
I might have an idea that could possibly split the gap.

Is the main concern that you're not seeing accurate times for the requests that otel phoenix is currently tracking? Is the fact that we aren't currently tracing certain requests a real concern?

**Comment by dvic** [comment]
I was typing a reply to the above, but let me reply first to this one, it's shorter ;)

> Is the main concern that you're not seeing accurate times for the requests that otel phoenix is currently tracking? Is the fact that we aren't currently tracing certain requests a real concern?

it's mainly about the former, about the accurate timings for the requests.

**Comment by dvic** [comment]
> Gotchas being you're now tracing every possible hit to the server which can quickly DDOS or escalate your trace generation without a significant amount of filtering which we don't currently have great facilities for. I'm probably an "advanced user" of otel in erlang/elixir and I wouldn't attempt it 😆

I see what you mean, indeed, there is more involved when you would move it to this layer.

> For the span stuff, if we cross process boundaries then we have to propagate the ctx. If we did do it with injecting headers again at the cowboy level, you will have to modify the existing headers by deleting the existing traceparent header before injecting the new one. I don't think the propagators currently support overwriting.

I was thinking something else here (although it's still a bit dirty): if there is no traceparent header -> generate one, otherwise don't do anything. But I'm not sure if context propagation works like this in the context of distributed tracing, is the traceparent header the context of the first span that was created that the request triggered in the system?

> I think what you've described would technically work but I don't think the spans would end up how you're expecting them. We'd still be creating a new span in Phoenix which would have all of the required info and a higher level span in cowboy which has much less. I do believe that is the only solution at this time, however. This is just a fundamental issue of how cowboy and everything else works, unfortunately.

Yeah you might be right, but still this problem of not having accurate durations bothers me :)

**Comment by dvic** [comment]
I've been playing around with the "naive" approach of setting the traceparent header:

![image](https://user-images.githubusercontent.com/1214337/127386014-c57e9c2a-6fbd-4ff2-bc34-8cef3d5dbb2d.png)

As you can see it's quite a difference (this is a very basic response but in `dev` not sure if that affects the performance significantly).

**Comment by dvic** [comment]
Just an update here, actually, the reason for the huge difference above is because the `Plug.Telemetry` is not measuring the whole `Endpoint`. If I put it on top, it's something like this:

![image](https://user-images.githubusercontent.com/1214337/127473207-8cc1d6bd-1eb1-40f1-bec1-05568d318026.png)

Doing an request with gzip only adds 30ms or so (the artificial response in this example is 906k unzipped):

![image](https://user-images.githubusercontent.com/1214337/127473306-d4459123-5410-427a-9724-fce0ac9163d0.png)

Conclusion: putting the `Plug.Telemetry` at the top of the endpoint already gives reasonable estimates of the real request duration.

**Comment by dvic** [comment]
The only issue for me currently is that errors in plugs are not caught, i.e., the spans are not ended because the stop event is not emitted. The comment in `Plug.Telemetry` also tells us this: *The :stop event is not guaranteed to be emitted in all error cases, so this Plug cannot be used as a Telemetry span.*. Maybe it's worthwhile pursuing a custom plug and/or using https://hexdocs.pm/plug/Plug.ErrorHandler.html instead of relying on `Plug.Telemetry` for creating the spans?

**Comment by dvic** [comment]
@bryannaegele what do you think of this last suggestion? (using a custom plug that uses `__before_compile__` to intercept errors)

**Comment by bryannaegele** [comment]
I have some thoughts I'm still working through that I'll try to wrap up when I have some time. This issue is getting closed as part of archiving this repo. Discussion can pick up in https://github.com/open-telemetry/opentelemetry-erlang-contrib/discussions/11 :)
