### ISSUE TITLE
liveview support

### ISSUE THREAD

**Issue by dvic** [opentelemetry-beam/opentelemetry_phoenix#30]
I'm working on a library, inspired by this one :), that traces Phoenix LiveView callbacks (based on https://hexdocs.pm/phoenix_live_view/telemetry.html). Is there interest to have this library support LiveView tracing? Or is it considered out of the scope? If so then I can open a PR in this repo to continue work there.

**Comment by dvic** [comment]
I have pushed the initial version at https://github.com/qdentity/opentelemetry_liveview, I haven't published anything yet.

**Comment by bryannaegele** [comment]
Nice. Derek Kraan and a couple of others have been working on liveview afaik and it won't be part of this library as they're quite different concerns; they're just in the same framework.

If you want to collaborate with them, there have been several recent discussions in the #opentelemetry channel on the Elixir slack. Most of these discussions tend to happen there or in the #observability-wg on the Erlang slack. I'm hoping to get everything consolidated to the official contrib repo so discussions, libraries, and efforts are more centralized but I'm still waiting on some setup from the otel admins.

**Comment by dvic** [comment]
I've reached out to Derek, I happen to know him :) I also joined the #opentelemetry Slack channel, thanks!

For now I'll just publish the library and once the contrib repo is set up I'll be happy to move the code into it 👍🏻
